services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mock-server:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

  app:
    build: .
    image: monitoring-service:v1.0
    container_name: monitoring-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mock-server
    environment:
      - SERVER_PORT=8080
      - SPRING_MONGODB_URI=mongodb://mongodb:27017/monitoring_db
      - EXTERNAL_MOCK_API_BASE_URL=http://mock-server:8080/mock-users

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  grafana_data: