spring:
  application:
    name: monitoring-service
  mongodb:
    uri: mongodb://localhost:27017/monitoring_db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: monitoring-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ajlekc.monitoringservice.event"

external:
  mock-api:
    base-url: http://localhost:8089/mock-users

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}