spring:
  application:
    name: monitoring-service
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://localhost:27017/monitoring_db}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: monitoring-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ajlekc.monitoringservice.event"

app:
  security:
    admin:
      username: admin
      password: admin
    user:
      username: user
      password: user

external:
  mock-api:
    base-url: ${EXTERNAL_MOCK_API_BASE_URL:http://localhost:8089/mock-users}

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  endpoint:
    health:
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}