spring:
  application:
    name: monitoring-service
  mongodb:
#    uri: mongodb://mongodb:27017/monitoring_db
    uri: mongodb://localhost:27017/testLocal

external:
  mock-api:
    base-url: https://jsonplaceholder.typicode.com/users

management:
  endpoints:
    web:
      exposure:
#        include: "health,info,env,prometheus"
        include: "health, prometheus"
  endpoint:
    health:
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}