apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: monitoring
  labels:
    app: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
        - name: app
          image: monitoring-service:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_MONGODB_URI
              value: "mongodb://mongodb:27017/monitoring_db"
            - name: EXTERNAL_MOCK_API_BASE_URL
              value: "http://wiremock:8080/mock-users"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9091"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
